### ISSUE TITLE
Implement class locator type

### ISSUE THREAD

**Issue by deki** [vmi/selenese-runner-java#173]
Class locator type currently results in UnsupportedOperationException.

I'm willing to implement this and create a pull request for it.

java.lang.UnsupportedOperationException: Unknown locator type: class=popup
	at jp.vmi.selenium.selenese.locator.WebDriverElementFinder.findElementsInternal(WebDriverElementFinder.java:218)
	at jp.vmi.selenium.selenese.locator.WebDriverElementFinder.findElements(WebDriverElementFinder.java:259)
	at jp.vmi.selenium.selenese.locator.WebDriverElementFinder.findElements(WebDriverElementFinder.java:271)
	at jp.vmi.selenium.selenese.locator.WebDriverElementFinder.findElement(WebDriverElementFinder.java:288)
	at com.thoughtworks.selenium.webdriven.commands.IsElementPresent.handleSeleneseCommand(IsElementPresent.java:36)
	at com.thoughtworks.selenium.webdriven.commands.IsElementPresent.handleSeleneseCommand(IsElementPresent.java:26)

**Comment by vmi** [comment]
Hi,

I welcome your pull request if you send it.

**Comment by deki** [comment]
Pull request is merged, so this issue can be closed.
