### ISSUE TITLE
Command line server for the IE driver has stopped working

### ISSUE THREAD

**Issue by dmartin-patientping** [vmi/selenese-runner-java#214]
Sadly I can't seem to find a way to get you more details on the crash. The output from selenium-runner is generic but below:

[2016-04-01 19:28:38.617 -04:00] [INFO] I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:18887: Connection reset
[2016-04-01 19:28:38.617 -04:00] [INFO] Retrying request to {}->http://localhost:18887

IE11 on windows 7.

**Comment by dmartin-patientping** [comment]
Different test suite, no dialog from windows indicating server died.
> [2016-04-01 20:20:18.137 -04:00] [INFO] baseURL: about:blank
> [2016-04-01 20:20:18.137 -04:00] [INFO] <1> Command#1: open("https://myserver/login")
> [2016-04-01 20:20:20.941 -04:00] [INFO] I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:24817: Connection reset
> [2016-04-01 20:20:20.941 -04:00] [INFO] Retrying request to {}->http://localhost:24817
> [2016-04-01 20:20:22.954 -04:00] [INFO] - [Success] Failed to get page information: [Error communicating with the remote browser. It may have died.]
> [2016-04-01 20:20:22.954 -04:00] [INFO] <2> Command#2: waitForElementPresent("id=username")
> org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
> Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
> System info: host: 'IE11Win7', ip: '10.0.2.15', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_101'
> Driver info: driver.version: RemoteWebDriver
> Capabilities [{browserAttachTimeout=0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, pageLoadStrategy=normal, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:24817/
> , javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss}]
> Session ID: 88c19f7a-a141-449a-842e-4e63245438e2
>         at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
>         at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.defaultContent(RemoteWebDriver.java:1039)
>         at jp.vmi.selenium.selenese.locator.WebDriverElementFinder.switchToFrame(WebDriverElementFinder.java:116)

**Comment by dmartin-patientping** [comment]
This is on selenium, not selenese-runner it seems:
https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/4178
