### ISSUE TITLE
Version 2.11.0 not working with Firefox 49, but FF 28 and 45 ESR work

### ISSUE THREAD

**Issue by manuelkiessling** [vmi/selenese-runner-java#219]
The latest 2.11.0 release of selenese-java-runner reproducibly doesn't work with Firefox 49.0, but works flawlessly with Firefox 28 and 45.4.0 ESR (all 64 bit on Ubuntu 14.04.5 LTS).

The Selenium run was started as follows:

```
/usr/bin/java \
  -jar /opt/selenese-runner-java/selenese-runner.jar \
  --driver firefox \
  --cli-args "--new-instance" \
  --cli-args "--profile /var/tmp/journeymonitor-firefox-profile-uhfeiruh" \
  --width 1920 \
  --height 1200 \
  --screenshot-on-fail /var/tmp/journeymonitor-screenshots \
  --strict-exit-code \
  test.html
```

The following is the error output:

```
org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows:
d.","homepageURL":null},{"locales":["ro"],"name":"Ubuntu Modifications","description":"Pachetul Ubuntu Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["ru"],"name":"Ubuntu Modifications","description":"???????????????????? Firefox ?????? Ubuntu","creator":"Canonical Ltd.","homepageURL":null},{"locales":["sl"],"name":"Ubuntu Modifications","description":"Ubuntu raz??iritve za Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["sv-SE"],"name":"Ubuntu Modifications","description":"Ubuntu-paket f??r Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["uk"],"name":"Ubuntu Modifications","description":"?????????????????????? ???????????????????? ???? Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-CN"],"name":"Ubuntu Modifications","description":"Ubuntu ???????????????.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-TW"],"name":"Ubuntu Modifications","description":"Ubuntu Firefox ????????????","creator":"Canonical Ltd.","homepageURL":null}],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"9.0","maxVersion":"37.0a1"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
1477380866454   DeferredSave.extensions.json    DEBUG   Save changes
1477380866454   addons.xpi  DEBUG   Updating database with changes to installed add-ons
1477380866454   addons.xpi-utils    DEBUG   Updating add-on states
1477380866454   addons.xpi-utils    DEBUG   Writing add-ons list
1477380866455   addons.xpi  DEBUG   Registering manifest for /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1477380866455   addons.xpi  DEBUG   Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1477380866456   addons.xpi  DEBUG   Registering manifest for /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1477380866456   addons.xpi  DEBUG   Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1477380866457   addons.xpi  DEBUG   Registering manifest for /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
1477380866457   addons.xpi  DEBUG   Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
1477380866458   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1477380866459   addons.manager  DEBUG   Provider finished startup: XPIProvider
1477380866459   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1477380866459   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1477380866459   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1477380866459   addons.manager  DEBUG   Starting provider: GMPProvider
1477380866464   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1477380866464   addons.manager  DEBUG   Provider finished startup: GMPProvider
1477380866464   addons.manager  DEBUG   Starting provider: PluginProvider
1477380866464   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1477380866464   addons.manager  DEBUG   Provider finished startup: PluginProvider
1477380866465   addons.manager  DEBUG   Completed startup sequence
1477380866933   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1477380866934   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1477380866935   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1477380866938   DeferredSave.extensions.json    DEBUG   Starting write
1477380867069   addons.repository   DEBUG   No addons.json found.
1477380867070   DeferredSave.addons.json    DEBUG   Save changes
1477380867074   DeferredSave.addons.json    DEBUG   Starting timer
1477380867086   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1477380867086   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1477380867087   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
1477380867090   DeferredSave.extensions.json    DEBUG   Write succeeded
1477380867090   addons.xpi-utils    DEBUG   XPI Database saved, setting schema version preference to 17
1477380867125   DeferredSave.addons.json    DEBUG   Starting write
1477380867132   DeferredSave.addons.json    DEBUG   Write succeeded

Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '002c44d51b0d', ip: '172.20.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.20-moby', java.version: '1.8.0_91'
Driver info: driver.version: FirefoxDriver
    at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:125)
    at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:128)
    at jp.vmi.selenium.webdriver.FirefoxDriverFactory.newInstance(FirefoxDriverFactory.java:165)
    at jp.vmi.selenium.webdriver.WebDriverManager$Builder.build(WebDriverManager.java:86)
    at jp.vmi.selenium.webdriver.WebDriverManager.get(WebDriverManager.java:312)
    at jp.vmi.selenium.selenese.Main.setupRunner(Main.java:133)
    at jp.vmi.selenium.selenese.Main.run(Main.java:82)
    at jp.vmi.selenium.selenese.Main.main(Main.java:213)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
d.","homepageURL":null},{"locales":["ro"],"name":"Ubuntu Modifications","description":"Pachetul Ubuntu Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["ru"],"name":"Ubuntu Modifications","description":"???????????????????? Firefox ?????? Ubuntu","creator":"Canonical Ltd.","homepageURL":null},{"locales":["sl"],"name":"Ubuntu Modifications","description":"Ubuntu raz??iritve za Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["sv-SE"],"name":"Ubuntu Modifications","description":"Ubuntu-paket f??r Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["uk"],"name":"Ubuntu Modifications","description":"?????????????????????? ???????????????????? ???? Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-CN"],"name":"Ubuntu Modifications","description":"Ubuntu ???????????????.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-TW"],"name":"Ubuntu Modifications","description":"Ubuntu Firefox ????????????","creator":"Canonical Ltd.","homepageURL":null}],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"9.0","maxVersion":"37.0a1"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
1477380866454   DeferredSave.extensions.json    DEBUG   Save changes
1477380866454   addons.xpi  DEBUG   Updating database with changes to installed add-ons
1477380866454   addons.xpi-utils    DEBUG   Updating add-on states
1477380866454   addons.xpi-utils    DEBUG   Writing add-ons list
1477380866455   addons.xpi  DEBUG   Registering manifest for /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1477380866455   addons.xpi  DEBUG   Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1477380866456   addons.xpi  DEBUG   Registering manifest for /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1477380866456   addons.xpi  DEBUG   Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1477380866457   addons.xpi  DEBUG   Registering manifest for /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
1477380866457   addons.xpi  DEBUG   Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
1477380866458   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1477380866459   addons.manager  DEBUG   Provider finished startup: XPIProvider
1477380866459   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1477380866459   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1477380866459   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1477380866459   addons.manager  DEBUG   Starting provider: GMPProvider
1477380866464   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1477380866464   addons.manager  DEBUG   Provider finished startup: GMPProvider
1477380866464   addons.manager  DEBUG   Starting provider: PluginProvider
1477380866464   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1477380866464   addons.manager  DEBUG   Provider finished startup: PluginProvider
1477380866465   addons.manager  DEBUG   Completed startup sequence
1477380866933   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1477380866934   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1477380866935   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1477380866938   DeferredSave.extensions.json    DEBUG   Starting write
1477380867069   addons.repository   DEBUG   No addons.json found.
1477380867070   DeferredSave.addons.json    DEBUG   Save changes
1477380867074   DeferredSave.addons.json    DEBUG   Starting timer
1477380867086   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1477380867086   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1477380867087   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
1477380867090   DeferredSave.extensions.json    DEBUG   Write succeeded
1477380867090   addons.xpi-utils    DEBUG   XPI Database saved, setting schema version preference to 17
1477380867125   DeferredSave.addons.json    DEBUG   Starting write
1477380867132   DeferredSave.addons.json    DEBUG   Write succeeded

    at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
    ... 11 more
[2016-10-25 07:35:11.358 +00:00] [INFO] Exit code: 1
```

**Comment by vmi** [comment]
Hi,

I released 3.0.0 which uses Selenium 3.x.
It works with Firefox 50.1.0.

Note:
* To use Firefox you need `geckodriver`.
* New FirefoxDriver does not yet support mouse related features.
