### ISSUE TITLE
Error in by setting remote firefox profile in Jenkins

### ISSUE THREAD

**Issue by shenlian8** [vmi/selenese-runner-java#229]
java -jar C:\selemium\selenese-runner.jar --driver remote --remote-url http://<server name>:4444/wd/hub --remote-browser firefox --profile default --screenshot-on-fail C:\selemium\screenshot --baseurl <base URL> C:\selemium\DTF1_1KN_Angestellter_SO.html

This is saved in a windows Batch file. It works under windows file expolorer by double clicking.

If it is intergrated into a Jenkins project, it show me the following error:

[2017-02-16 16:02:49.563 +01:00] [INFO] Start: Selenese Runner 3.1.0
[2017-02-16 16:02:49.724 +01:00] [INFO] Remote browser: firefox
[2017-02-16 16:02:49.724 +01:00] [INFO] Firefox profile: default
java.lang.NullPointerException
	at jp.vmi.selenium.webdriver.FirefoxDriverFactory.setFirefoxProfile(FirefoxDriverFactory.java:156)
	at jp.vmi.selenium.webdriver.FirefoxDriverFactory.setDriverSpecificCapabilities(FirefoxDriverFactory.java:50)
	at jp.vmi.selenium.webdriver.RemoteWebDriverFactory.newInstance(RemoteWebDriverFactory.java:40)
	at jp.vmi.selenium.webdriver.WebDriverManager$Builder.build(WebDriverManager.java:77)
	at jp.vmi.selenium.webdriver.WebDriverManager.get(WebDriverManager.java:266)
	at jp.vmi.selenium.selenese.Main.setupRunner(Main.java:139)
	at jp.vmi.selenium.selenese.Main.run(Main.java:82)
	at jp.vmi.selenium.selenese.Main.main(Main.java:221)
[2017-02-16 16:02:49.724 +01:00] [INFO] Exit code: 1

Would you please check it? Thanks a lot!

Lian Shen

**Comment by vmi** [comment]
Hi,

I confirmed that NullPointerException will be thrown if you specify a nonexistent profile.
(I regard this as a bug)

As a result of checking my Firefox profile settings (Mac: ~/Application Support/Firefox/profiles.ini), there is a profile named like `default-0000000000000` instead of a profile named `default`.

Please check the profile name of your environment.

**Comment by shenlian8** [comment]
Hi,

thank you very much for the quick response!

Today I have done some tests and can comfirm you that is not a bug of selenese-runner-java.

The problem is just that the selenese-runner-java cannot find the firefox profile under Jenkins enviroment.

The solution is copy the firefox profile to an avalebale path for Jenkins and use --profile-dir option.

The selenese-runner-java is a very nice job. Tanks again!

Best regards

Lian Shen
