### ISSUE TITLE
Combination of Selenese Runner 3.2.0 and Geckodriver 0.15.0 and Firefox 52.0 not working

### ISSUE THREAD

**Issue by manuelkiessling** [vmi/selenese-runner-java#232]
With Selenese Runner at 3.2.0, Geckodriver at 0.15.0, and Firefox at 52.0 I cannot run a testcase (tried on Mac OS X with Oracle Java 1.8.0_102):

```
> /usr/bin/java -jar ./selenese-runner.jar --driver firefox --geckodriver ./geckodriver --width 1920 --height 1200 --strict-exit-code --timeout 120000 ./test.html

[2017-03-11 14:14:06.436 +01:00] [INFO] Start: Selenese Runner 3.2.0
1489238047132	geckodriver	INFO	Listening on 127.0.0.1:46672
[2017-03-11 14:14:07.177 +01:00] [INFO] Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1489238047389	mozprofile::profile	INFO	Using profile path /var/folders/r_/2lzmp42d7b7c4bwm7q4fpbhr0000gn/T/rust_mozprofile.GlubeiCXwpoQ
1489238047398	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args []
1489238047400	geckodriver::marionette	INFO	Connecting to Marionette on localhost:64801
1489238047600	addons.manager	DEBUG	Application has been upgraded
1489238047636	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1489238047639	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1489238047644	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1489238047647	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1489238047647	addons.manager	DEBUG	Starting provider: XPIProvider
1489238047647	addons.xpi	DEBUG	startup
1489238047648	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1489238047649	addons.xpi	INFO	Mapping aushelper@mozilla.org to /Applications/Firefox.app/Contents/Resources/browser/features/aushelper@mozilla.org.xpi
1489238047649	addons.xpi	INFO	Mapping e10srollout@mozilla.org to /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1489238047649	addons.xpi	INFO	Mapping firefox@getpocket.com to /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1489238047649	addons.xpi	INFO	Mapping webcompat@mozilla.org to /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1489238047650	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to /Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1489238047650	addons.xpi	DEBUG	checkForChanges
1489238047650	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1489238047651	addons.xpi	DEBUG	Loaded add-on state from prefs: {}
1489238047652	addons.xpi	DEBUG	New add-on aushelper@mozilla.org in app-system-defaults
1489238047652	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1489238047652	addons.xpi	DEBUG	New add-on e10srollout@mozilla.org in app-system-defaults
1489238047653	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1489238047653	addons.xpi	DEBUG	New add-on firefox@getpocket.com in app-system-defaults
1489238047653	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1489238047654	addons.xpi	DEBUG	New add-on webcompat@mozilla.org in app-system-defaults
1489238047654	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1489238047654	addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1489238047654	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1489238047655	addons.xpi	DEBUG	getInstallState changed: true, state: {"app-system-defaults":{"aushelper@mozilla.org":{"d":"/Applications/Firefox.app/Contents/Resources/browser/features/aushelper@mozilla.org.xpi","st":1488960993000},"e10srollout@mozilla.org":{"d":"/Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi","st":1488960993000},"firefox@getpocket.com":{"d":"/Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi","st":1488960993000},"webcompat@mozilla.org":{"d":"/Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi","st":1488960993000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","st":1488960993000}}}
1489238047660	addons.xpi-utils	DEBUG	Opening XPI database /var/folders/r_/2lzmp42d7b7c4bwm7q4fpbhr0000gn/T/rust_mozprofile.GlubeiCXwpoQ/extensions.json
1489238047661	addons.xpi-utils	DEBUG	New add-on aushelper@mozilla.org installed in app-system-defaults
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1489238047670	DeferredSave.extensions.json	DEBUG	Save changes
1489238047670	addons.xpi-utils	DEBUG	New add-on e10srollout@mozilla.org installed in app-system-defaults
1489238047672	DeferredSave.extensions.json	DEBUG	Starting timer
1489238047674	DeferredSave.extensions.json	DEBUG	Save changes
1489238047674	addons.xpi-utils	DEBUG	New add-on firefox@getpocket.com installed in app-system-defaults
1489238047678	DeferredSave.extensions.json	DEBUG	Save changes
1489238047678	addons.xpi-utils	DEBUG	New add-on webcompat@mozilla.org installed in app-system-defaults
1489238047681	DeferredSave.extensions.json	DEBUG	Save changes
1489238047682	addons.xpi-utils	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
1489238047685	DeferredSave.extensions.json	DEBUG	Save changes
1489238047685	addons.manager	DEBUG	Registering startup change 'installed' for aushelper@mozilla.org
1489238047696	addons.xpi	DEBUG	Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/aushelper@mozilla.org.xpi
1489238047701	addons.xpi	DEBUG	Calling bootstrap method install on aushelper@mozilla.org version 2.0
1489238047701	addons.xpi-utils	DEBUG	Make addon app-system-defaults:aushelper@mozilla.org visible
1489238047701	DeferredSave.extensions.json	DEBUG	Save changes
1489238047702	addons.manager	DEBUG	Registering startup change 'installed' for e10srollout@mozilla.org
1489238047703	addons.xpi	DEBUG	Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1489238047704	addons.xpi	DEBUG	Calling bootstrap method install on e10srollout@mozilla.org version 1.9
1489238047706	addons.xpi-utils	DEBUG	Make addon app-system-defaults:e10srollout@mozilla.org visible
1489238047706	DeferredSave.extensions.json	DEBUG	Save changes
1489238047706	addons.manager	DEBUG	Registering startup change 'installed' for firefox@getpocket.com
1489238047707	addons.xpi	DEBUG	Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1489238047709	addons.xpi	DEBUG	Calling bootstrap method install on firefox@getpocket.com version 1.0.5
1489238047710	addons.xpi-utils	DEBUG	Make addon app-system-defaults:firefox@getpocket.com visible
1489238047710	DeferredSave.extensions.json	DEBUG	Save changes
1489238047710	addons.manager	DEBUG	Registering startup change 'installed' for webcompat@mozilla.org
1489238047710	addons.xpi	DEBUG	Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1489238047711	addons.xpi	DEBUG	Calling bootstrap method install on webcompat@mozilla.org version 1.0
1489238047711	addons.xpi-utils	DEBUG	Make addon app-system-defaults:webcompat@mozilla.org visible
1489238047712	DeferredSave.extensions.json	DEBUG	Save changes
1489238047712	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1489238047712	DeferredSave.extensions.json	DEBUG	Save changes
1489238047712	addons.xpi	DEBUG	Updating XPIState for {"id":"aushelper@mozilla.org","syncGUID":"{d84af6b3-268c-2545-a692-3db498570ddf}","location":"app-system-defaults","version":"2.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Application Update Service Helper","description":"Sets value(s) in the update url based on custom checks.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/features/aushelper@mozilla.org.xpi","installDate":1488960993000,"updateDate":1488960993000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":8486,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1489238047712	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1489238047713	addons.xpi	DEBUG	Updating XPIState for {"id":"e10srollout@mozilla.org","syncGUID":"{00c11e37-8fcf-0a44-a663-d0687da2735d}","location":"app-system-defaults","version":"1.9","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Multi-process staged rollout","description":"Staged rollout of Firefox multi-process feature.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi","installDate":1488960993000,"updateDate":1488960993000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":7181,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1489238047713	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1489238047713	addons.xpi	DEBUG	Updating XPIState for {"id":"firefox@getpocket.com","syncGUID":"{e2b6210b-1f1a-2d48-a378-baa570825534}","location":"app-system-defaults","version":"1.0.5","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Pocket","description":"When you find something you want to view later, put it in Pocket.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi","installDate":1488960993000,"updateDate":1488960993000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":920279,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1489238047713	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1489238047713	addons.xpi	DEBUG	Updating XPIState for {"id":"webcompat@mozilla.org","syncGUID":"{216556b3-c0c0-b44e-97af-c063ca594e55}","location":"app-system-defaults","version":"1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Web Compat","description":"Urgent post-release fixes for web compatibility.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi","installDate":1488960993000,"updateDate":1488960993000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":1454,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1489238047714	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1489238047714	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"{ea4aa32e-2986-0748-a977-43b10d017f21}","location":"app-global","version":"52.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1488960993000,"updateDate":1488960993000,"applyBackgroundUpdates":1,"skinnable":true,"size":6346,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.0"}],"targetPlatforms":[],"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false}
1489238047714	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1489238047715	DeferredSave.extensions.json	DEBUG	Save changes
1489238047715	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1489238047715	addons.xpi-utils	DEBUG	Updating add-on states
1489238047715	addons.xpi-utils	DEBUG	Writing add-ons list
1489238047716	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/aushelper@mozilla.org.xpi
1489238047716	addons.xpi	DEBUG	Calling bootstrap method startup on aushelper@mozilla.org version 2.0
1489238047717	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1489238047717	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.9
1489238047718	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1489238047718	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1489238047719	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1489238047719	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1489238047721	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1489238047721	addons.manager	DEBUG	Provider finished startup: XPIProvider
1489238047721	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1489238047721	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1489238047721	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1489238047722	addons.manager	DEBUG	Starting provider: GMPProvider
1489238047727	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1489238047727	addons.manager	DEBUG	Provider finished startup: GMPProvider
1489238047727	addons.manager	DEBUG	Starting provider: PluginProvider
1489238047727	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1489238047727	addons.manager	DEBUG	Provider finished startup: PluginProvider
1489238047728	addons.manager	DEBUG	Completed startup sequence
1489238047904	Marionette	INFO	Listening on port 64801
1489238048085	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1489238048085	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1489238048085	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1489238048119	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1489238048120	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1489238048121	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1489238048124	DeferredSave.extensions.json	DEBUG	Starting write
1489238048233	DeferredSave.extensions.json	DEBUG	Write succeeded
1489238048233	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
[2017-03-11 14:14:09.216 +01:00] [INFO] Falling back to original OSS JSON Wire Protocol.
[2017-03-11 14:14:09.226 +01:00] [INFO] Falling back to straight W3C remote end connection
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{firefox_binary=FirefoxBinary(/Applications/Firefox.app/Contents/MacOS/firefox-bin), marionette=true, firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@4cc8eb05, browserName=firefox, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@4cc8eb05, version=, platform=ANY, firefox_profile=org.openqa.selenium.firefox.F...}], required capabilities = Capabilities [{}]
Build info: version: '3.0.1', revision: 'unknown', time: 'unknown'
System info: host: 'MacBook-Pro-3.fritz.box', ip: '192.168.178.55', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.3', java.version: '1.8.0_102'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:259)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:135)
	at jp.vmi.selenium.webdriver.FirefoxDriverFactory.newInstance(FirefoxDriverFactory.java:182)
	at jp.vmi.selenium.webdriver.WebDriverManager$Builder.build(WebDriverManager.java:77)
	at jp.vmi.selenium.webdriver.WebDriverManager.get(WebDriverManager.java:266)
	at jp.vmi.selenium.selenese.Main.setupRunner(Main.java:139)
	at jp.vmi.selenium.selenese.Main.run(Main.java:82)
	at jp.vmi.selenium.selenese.Main.main(Main.java:221)
[2017-03-11 14:14:09.233 +01:00] [INFO] Exit code: 1
```

However, I have verified that updating the Selenium dependency of Selenese Runner at a6ca894010ac2d426f81b22a61a6b4229a75fcf6 to 3.3.1 results in a working setup.

**Comment by fimash** [comment]
Use Selenium 3.3.1 https://selenium-release.storage.googleapis.com/index.html?path=3.3/

**Comment by vmi** [comment]
Hi,
I fixed the problem and released new version.
Please test it.

**Comment by vmi** [comment]
Hi,
If your problem is not resolved in the current release, please reopen this issue.
