### ISSUE TITLE
How to remote control myself

### ISSUE THREAD

**Issue by lucdel** [vmi/selenese-runner-java#248]
Hello,

My problem is simple. I want to use a profile while running my test on Firefox. But this imply to remote control myself : 

_"--profile-dir (-P) <dir>                : profile directory (Firefox only *1)
*1 It is available if using "--driver remote --remote-browser firefox"."_

But I can't find any information about the remote controlling. I just want to launch the navigator on my computer ( as Selenium IDE does) but whatever I put in the  --remote-url option, the connexion seem to be refused. 

I guess there is more to do to allow selenese-runner to remote control myself.

**Comment by lucdel** [comment]
To add some information. I try 
java  -jar  Lib/selenese-runner.jar  --geckodriver="Drivers/geckodriver.exe"   -P "./ProfilFirefox" --driver remote --remote-browser firefox   --remote-url "http://127.0.0.1:4444" --define acceptInsecureCerts:bool=true --xml-result RapportXMLFirefox "./SuiteDeTest1.html"

and get

org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'ITEM-S36945', ip: '172.20.181.149', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: RemoteWebDriver
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:174)
        at jp.vmi.selenium.webdriver.RemoteWebDriverFactory.newInstance(RemoteWebDriverFactory.java:66)
        at jp.vmi.selenium.webdriver.WebDriverManager$Builder.build(WebDriverManager.java:77)
        at jp.vmi.selenium.webdriver.WebDriverManager.get(WebDriverManager.java:266)
        at jp.vmi.selenium.selenese.Main.setupRunner(Main.java:146)
        at jp.vmi.selenium.selenese.Main.run(Main.java:89)
        at jp.vmi.selenium.selenese.Main.main(Main.java:263)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4444 [/127.0.0.1] failed: Connection refused: connect
