### ISSUE TITLE
Trouble with startup of webdrivers using selenese-runner

### ISSUE THREAD

**Issue by Robldibobl** [vmi/selenese-runner-java#255]
Hello there,

I have to automate some browser tests using selenium and they want me to integrate these tests in Bamboo. This tool is the optimal choice for me, but I still have some issues/questions to figure out.

1.) When using Firefox (v46.0.1 installed on the server bamboo is on), it can't seem to start it. I read while researching that v47 and earlier are not supported with the geckodriver. Is there a way though to make it work? (Sorry, this one is quite off-topic) Error message: [](http://prntscr.com/g8npz8)

2.) When using IE (version currently unknown), it won't start because of the protected mode which isn't the same in all zones. Is there an option I can call to alter this? Error message: [](http://prntscr.com/g8nue0)

3.) When using Chrome (version currently unknown), I get an "access denied" error and it instantly quits. No idea what to do, but searching for the issue has not brought up any solutions yet. Please, if you'd have some hints for me.. Error message: [](http://prntscr.com/g8nwnt)

4.) Microsoft Edge is not supported at all? I saw the webdriver microsoft is offering, but haven't seen any way to use it with selenese-runner. Did I just miss everything or is it just not a thing?

Thanks

**Comment by Robldibobl** [comment]
Some updates on my progress:

**Chrome** build plans are running, everything's good here.

**Firefox** has been updated by a guy with permissions, now this 
<details>
<summary>Log snippet - click to expand</summary><p>

```build	25-Aug-2017 12:28:24	C:\bamboo-agent\home\xml-data\build-dir\XBSV7-SEL-JOB1>java -jar selenium-test/selenese-runner.jar --driver firefox --geckodriver selenium-test/src/test/resources/drivers/geckodriver.exe --xml-result selenium-test/log/firefox selenium-test/src/test/resources/selenium_cc_recordings/automated_testcases/0_TestSuite/LocalizationTestSuite 

build	25-Aug-2017 12:28:25	[2017-08-25 12:28:25.701 +02:00] [INFO] Start: Selenese Runner 3.7.0

error	25-Aug-2017 12:28:27	1503656907682	geckodriver	INFO	geckodriver 0.18.0

error	25-Aug-2017 12:28:27	1503656907698	geckodriver	INFO	Listening on 127.0.0.1:7770

error	25-Aug-2017 12:28:28	1503656908650	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]

error	25-Aug-2017 12:28:32	1503656912572	Marionette	INFO	Listening on port 62788

build	25-Aug-2017 12:28:35	[2017-08-25 12:28:35.235 +02:00] [INFO] Detected dialect: W3C

build	25-Aug-2017 12:28:35	[2017-08-25 12:28:35.250 +02:00] [INFO] Initial window size: system default 

build	25-Aug-2017 12:28:35	[2017-08-25 12:28:35.250 +02:00] [INFO] Initialized: FirefoxDriver

build	25-Aug-2017 12:28:35	[2017-08-25 12:28:35.453 +02:00] [INFO] HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)

error	25-Aug-2017 12:28:35	org.openqa.selenium.WebDriverException: setTimeouts

error	25-Aug-2017 12:28:35	Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'

error	25-Aug-2017 12:28:35	System info: host: 'VMBAMBOOSLAVE01', ip: '10.1.100.101', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_65'

error	25-Aug-2017 12:28:35	Driver info: org.openqa.selenium.firefox.FirefoxDriver

error	25-Aug-2017 12:28:35	Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20161219140923, version=51.0, platform=XP, proxy=Proxy(), command_id=1.0, specificationLevel=0.0, acceptSslCerts=false, processId=5820.0, browserVersion=51.0, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, javascriptEnabled=true, platformName=windows_nt}]

error	25-Aug-2017 12:28:35	Session ID: 55cd4c28-c56a-497f-8329-d9c6445570f6

error	25-Aug-2017 12:28:35		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

error	25-Aug-2017 12:28:35		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

error	25-Aug-2017 12:28:35		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

error	25-Aug-2017 12:28:35		at java.lang.reflect.Constructor.newInstance(Constructor.java:422)

error	25-Aug-2017 12:28:35		at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)

error	25-Aug-2017 12:28:35		at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)

error	25-Aug-2017 12:28:35		at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)

error	25-Aug-2017 12:28:35		at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)

error	25-Aug-2017 12:28:35		at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)

error	25-Aug-2017 12:28:35		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)

error	25-Aug-2017 12:28:35		at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.pageLoadTimeout(RemoteWebDriver.java:880)

error	25-Aug-2017 12:28:35		at jp.vmi.selenium.selenese.Runner.setDriverTimeout(Runner.java:398)

build	25-Aug-2017 12:28:35	[2017-08-25 12:28:35.469 +02:00] [INFO] Exit code: 1

error	25-Aug-2017 12:28:35		at jp.vmi.selenium.selenese.Runner.setDriver(Runner.java:249)

error	25-Aug-2017 12:28:35		at jp.vmi.selenium.selenese.Main.setupRunner(Main.java:146)

error	25-Aug-2017 12:28:35		at jp.vmi.selenium.selenese.Main.run(Main.java:89)

error	25-Aug-2017 12:28:35		at jp.vmi.selenium.selenese.Main.main(Main.java:263)

build	25-Aug-2017 12:28:35	[2017-08-25 12:28:35.484 +02:00] [INFO] HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)

build	25-Aug-2017 12:28:36	[2017-08-25 12:28:36.202 +02:00] [WARN] quit

build	25-Aug-2017 12:28:36	Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'

build	25-Aug-2017 12:28:36	System info: host: 'VMBAMBOOSLAVE01', ip: '10.1.100.101', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_65'

build	25-Aug-2017 12:28:36	Driver info: org.openqa.selenium.firefox.FirefoxDriver

build	25-Aug-2017 12:28:36	Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20161219140923, version=51.0, platform=XP, proxy=Proxy(), command_id=1.0, specificationLevel=0.0, acceptSslCerts=false, processId=5820.0, browserVersion=51.0, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, javascriptEnabled=true, platformName=windows_nt}]

build	25-Aug-2017 12:28:36	Session ID: 55cd4c28-c56a-497f-8329-d9c6445570f6

build	25-Aug-2017 12:28:36	[2017-08-25 12:28:36.202 +02:00] [INFO] Quit: FirefoxDriver
```

</p></details>


comes up.

**Internet Explorer** still no progress on the protected mode issue.

**Comment by vmi** [comment]
Hi,

I apologize for replying late.

As a premise, SeleneseRunner follows the latest Selenium.
Selenium often breaks backward compatibility. (but the version number does not include that information)
However, as a countermeasure to this problem, it is difficult for me to maintain multiple versions of SeleneseRunner.

1.) I think that I can not support this problem. I understand that the latest Selenium does not support Firefox without GeckoDriver.
If I have misunderstood, please provide information on that.

2.) If the latest Selenium can use on IE, the problem is a bug of SeleneseRunner.
If you have information on how to use Selenum with IE, please provide it.
Otherwise, I will investigate the problem, but please understand that it will take time.

4.) It is similar to the problem of IE.

**Comment by Robldibobl** [comment]
Thanks for replying!

1.) I finally found something that solves my problem for Firefox. There was a bug with Firefox v54 and lower where the 'maximizeWindow()' selenese command resulted in a NullPointerException. I could upgrade on the test system to v55 and with your updated version, it works with Firefox.

2.) It seems today is the day where I think I'm the most stupid person alive. I finally found what I had to do with the IE protected mode settings. I figured it out (pushing the security level in all zones to high **AND** checking the checkbox at the bottom of every single zone). This should also solve my problem with IE.

4.) Now to Edge. Kindly asking, are there options implemented (like for firefox/chrome à la --firefox/--chrome) to access and specify the MS Edge webdriver?
This is not necessary for my testing purposes, but I think selenese-runner would be a more complete allround solution with Edge support.
If it's something I can pull off, I'd like to try my best to help with this one.

As always, many thanks for providing help and this piece of software.

**Comment by nileshzarkar** [comment]
Hi,
Can I hope for a IE 11 support anytime soon ?
