### ISSUE TITLE
NoSuchFieldError: ISO_8601_EXTENDED_DATETIME_TIME_ZONE_FORMAT

### ISSUE THREAD

**Issue by amirjamak** [vmi/selenese-runner-java#275]
Hi,
I am getting this error, during the execution. Maybe I am doing something wrong?
Thanks Amir

`[2018-06-29 14:43:11.947] [INFO] [main] [j.v.h.r.HtmlResult.generate:185] - Make the directory for HTML resut: target/site/selenium-reports
[2018-06-29 14:43:12.318] [INFO] [main] [j.v.h.r.HtmlResult.generate:203] - Generated HTML result: target/site/selenium-reports/TEST-PublicPage_0001_HomepageSuit.html
[2018-06-29 14:43:12.326] [INFO] [main] [j.v.h.r.HtmlResult.generate:203] - Generated HTML result: target/site/selenium-reports/TEST-PublicPage.html
java.lang.NoSuchFieldError: ISO_8601_EXTENDED_DATETIME_TIME_ZONE_FORMAT
	at jp.vmi.junit.result.TestResult.getTimestamp(TestResult.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.xml.internal.bind.v2.runtime.reflect.Accessor$GetterSetterReflection.get(Accessor.java:343)
	at com.sun.xml.internal.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.print(TransducedAccessor.java:224)
	at com.sun.xml.internal.bind.v2.runtime.property.AttributeProperty.serializeAttributes(AttributeProperty.java:86)
	at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeAttributes(ClassBeanInfoImpl.java:368)
	at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsSoleContent(XMLSerializer.java:576)
	at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeRoot(ClassBeanInfoImpl.java:326)
	at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsRoot(XMLSerializer.java:479)
	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:308)
	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:236)
	at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:103)
	at jp.vmi.junit.result.JUnitResult.endTestSuite(JUnitResult.java:118)
	at jp.vmi.selenium.selenese.inject.ExecuteTestSuiteInterceptor.invoke(ExecuteTestSuiteInterceptor.java:63)
	at jp.vmi.selenium.selenese.inject.AbstractExecuteTestSuiteInterceptor.invoke(AbstractExecuteTestSuiteInterceptor.java:29)
	at jp.vmi.selenium.selenese.TestSuite.execute(TestSuite.java:185)
	at jp.vmi.selenium.selenese.inject.ExecuteTestSuiteInterceptor.invoke(ExecuteTestSuiteInterceptor.java:49)
	at jp.vmi.selenium.selenese.inject.AbstractExecuteTestSuiteInterceptor.invoke(AbstractExecuteTestSuiteInterceptor.java:29)
	at jp.vmi.selenium.selenese.Runner.execute(Runner.java:658)
	at jp.vmi.selenium.selenese.Runner.run(Runner.java:702)
	at jp.vmi.selenium.selenese.Main.run(Main.java:91)
	at jp.vmi.selenium.selenese.Main.main(Main.java:269)
[2018-06-29 14:43:12.343] [INFO] [main] [j.v.s.s.Main.exit:246] - Exit code: 1`

**Comment by vmi** [comment]
Hi,

Thank you for the report.
Sorry I'm late.

Please tell me how to reproduce this problem because I could not do it.
It seems to me that this problem is caused by using the old commons-lang3.
