### ISSUE TITLE
alert/verifyConfirmation don't work

### ISSUE THREAD

**Issue by vmi** [vmi/selenese-runner-java#32]
[2012-09-03 23:13:21.000] [INFO] Command#18: verifyConfirmation("***")
[2012-09-03 23:13:21.000] [ERROR] getConfirmation()
[2012-09-03 23:13:21.015] [ERROR] There were no confirmations
(snip)
[2012-09-03 23:13:21.015] [ERROR] There were no confirmations
[2012-09-03 23:13:21.046] [INFO] End(48.7sec): TestSuite[default-00]
com.thoughtworks.selenium.SeleniumException: There were no confirmations
        at org.openqa.selenium.internal.seleniumemulation.AlertOverride.getNextConfirmation(AlertOverride.java:69)
        at org.openqa.selenium.internal.seleniumemulation.GetConfirmation.handleSeleneseCommand(GetConfirmation.java:30)
        at org.openqa.selenium.internal.seleniumemulation.SeleneseCommand.apply(SeleneseCommand.java:29)
        at org.openqa.selenium.internal.seleniumemulation.Timer.run(Timer.java:38)
        at org.openqa.selenium.WebDriverCommandProcessor.execute(WebDriverCommandProcessor.java:144)
        at org.openqa.selenium.WebDriverCommandProcessor.doCommand(WebDriverCommandProcessor.java:74)
        at jp.vmi.selenium.selenese.TestCase.doBuiltInCommand(TestCase.java:110)
        at jp.vmi.selenium.selenese.command.Assertion.doCommand(Assertion.java:82)
        at jp.vmi.selenium.selenese.TestCase.doCommand(TestCase.java:242)
        at jp.vmi.selenium.selenese.inject.CommandLogInterceptor.invoke(CommandLogInterceptor.java:100)
        at jp.vmi.selenium.selenese.TestCase.execute(TestCase.java:251)
        at jp.vmi.selenium.selenese.inject.ExecuteTestCaseInterceptor.invoke(ExecuteTestCaseInterceptor.java:44)
        at jp.vmi.selenium.selenese.TestSuite.execute(TestSuite.java:86)
        at jp.vmi.selenium.selenese.inject.ExecuteTestSuiteInterceptor.invoke(ExecuteTestSuiteInterceptor.java:32)
        at jp.vmi.selenium.selenese.Runner.run(Runner.java:161)
        at jp.vmi.selenium.selenese.Main.run(Main.java:237)
        at jp.vmi.selenium.selenese.Main.main(Main.java:257)
[2012-09-03 23:13:21.312] [WARN] null

**Comment by vmi** [comment]
I re-enabled alert/confirm commands.
Because Selenium supported the feature with `localStorage`.
